name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  skip_duplicate_jobs:
    name: Skip duplicate jobs
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md", "**/docs/**", "**/.gitignore", "**/LICENSE"]'
          concurrent_skipping: same_content_newer

  run_tests_and_build:
    name: Run tests and build
    runs-on: ubuntu-latest
    needs: skip_duplicate_jobs
    if: needs.skip_duplicate_jobs.outputs.should_skip != 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK (Temurin 17)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Gradle artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled_jar_files
          path: build/libs/
